### ISSUE TITLE
Register package?

### ISSUE THREAD

**Issue by IlyaOrson** [timholy/QuadDIRECT.jl#19]
It would be nice to be able to install this without the github url :)

**Comment by timholy** [comment]
You can. Add [this registry](https://github.com/HolyLab/HolyLabRegistry).

**Comment by IlyaOrson** [comment]
My misunderstanding was because I could not find this package in JuliaHub or the general registry. I opened [this issue](https://github.com/JuliaComputing/JuliaHub/issues/80) on JuliaHub to increase the visibility of packages in public registries apart from the general registry.
