### ISSUE TITLE
Register to General?

### ISSUE THREAD

**Issue by ChrisRackauckas** [timholy/QuadDIRECT.jl#25]
I see tags but it's not clear to me where this is registered since it doesn't seem to be to General?

**Comment by timholy** [comment]
https://github.com/HolyLab/HolyLabRegistry

(I'm still not "back" but I happened to notice this on my phone; I'm hoping to start coming back this coming week or next...)

FYI a big part of my "sabbatical" has been to finally develop the package to replace this one. It's still not clear how well it will work but all indications are that it will be deterministic (always find the global optimum) and fast (no intrinsic "curse of dimensionality," aiming for a runtime ∝(time of a convex local minimizer)*(number of "competitive" minima)). Those are extremely ambitious goals and it's not yet clear that both will be achieved, but if we even get most of the way there it will be a New Thing that no one but Julia has.

But it will be limited to problems where you can plausibly compute and store lots of Hessians, so don't expect it to be useful for problems with tons of parameters.

**Comment by ChrisRackauckas** [comment]
>FYI a big part of my "sabbatical" has been to finally develop the package to replace this one. It's still not clear how well it will work but all indications are that it will be deterministic (always find the global optimum) and fast (no intrinsic "curse of dimensionality," aiming for a runtime ∝(time of a convex local minimizer)*(number of "competitive" minima)). Those are extremely ambitious goals and it's not yet clear that both will be achieved, but if we even get most of the way there it will be a New Thing that no one but Julia has.

Cool, I'll tell everyone you have the ultimate guaranteed global optimizer coming and hype it up.

>But it will be limited to problems where you can plausibly compute and store lots of Hessians, so don't expect it to be useful for problems with tons of parameters.

And leave out this detail. You'll solve it, right? 😉

**Comment by timholy** [comment]
> You'll solve it, right?

Nope. There's basically a theorem about that: https://link.springer.com/content/pdf/10.1007/BF01096455.pdf. The Hessians should allow me to plant `~1` flag near each competitive local minimum; without them you have a whole bunch of flags (`~k^d` where `d` is the dimensionality) around each minimum.

More concretely, there might be some cases where something can be done, but I don't think it will qualify as "solving" it.

My bigger hope is that the combination of sparsity and smarts from an eventual Diffractor.jl (which I've not followed closely) will suffice for a ton of interesting problems. And of course, there are interesting low-dimensional problems. Heck, I'd be happy with a really good rigid-body alignment algorithm, and that's only 6 parameters.

**Comment by ChrisRackauckas** [comment]
Sparse Hessian coloring exists, but the differentiation decompression scheme is missing. I'll get a student to finish that up. But generally I think the interesting thing will be the Symbolics.jl-traced Hessians mixed with E-graph simplifications. Yeah, this will be fun.

**Comment by timholy** [comment]
Closed by d6170f14a49f57552c59c9b4533a4b75a3ab3c45
