### ISSUE TITLE
Installation and Github authentication

### ISSUE THREAD

**Issue by EngrStudent** [timholy/QuadDIRECT.jl#26]
I am trying to work through this: https://benchmarks.sciml.ai/html/ParameterEstimation/LorenzParameterEstimation.html    

I started with a clean julia package and was working through adding stuff.  My Julia version is 1.7.2, and I am working in JuPyTeR notebook (6.4.5) using Python 3.9.7 on a 64 Windows machine.

The code has these as the libraries. but they don't all come with base Julia:    
```
using ParameterizedFunctions, OrdinaryDiffEq, DiffEqParamEstim
using BlackBoxOptim, NLopt, Plots, QuadDIRECT
```

So I made this as my set of installations:    
```
using Pkg
Pkg.add("ParameterizedFunctions")
Pkg.add("OrdinaryDiffEq")
Pkg.add("DiffEqParamEstim")
Pkg.add("BlackBoxOptim")
Pkg.add("NLopt")
Pkg.add("Plots")
Pkg.add("QuadDIRECT")
```

It has a problem when it gets to "QuadDIRECT", and it gives me this error:    
```
The following package names could not be resolved:
 * QuadDIRECT (not found in project, manifest or registry)
```

When I searched, I found "QuadDirect" here:     
https://juliapackages.com/p/quaddirect

It's presence on the Julia Packages list suggest some other sort of error, but I'm new the the language and don't know its quirks.

I then found this (other links) which suggests that I modify the add command.  

So I tried this:   
`Pkg.add(url="https://github.com/timholy/QuadDIRECT")`

It wanted me to authenticate, but then the authentication failed over and over.  I opened a browser window and it worked fine but required 2-factor, so it seems to be a problem on the part of the Julia-based access to Github.

It gives this error:    
`failed to clone from https://github.com/timholy/QuadDIRECT, error: GitError(Code:EUSER, Class:Callback, Aborting, user cancelled credential request.)`

What am I doing wrong in installing this package?

**Comment by mdhe1248** [comment]
Although I am not the author of this package..., you may wanna check https://github.com/timholy/QuadDIRECT.jl/issues/25#issuecomment-836555127

**Comment by timholy** [comment]
Understandable confusion; that Lorenz writeup might want to suggest adding HolyLabRegistry. I clarified this in the README, there is now a prominent link.
